### ISSUE TITLE
[FEAT] NavBar 구현

### ISSUE THREAD

**Issue by jh2ee** [Hongmoon-gak/Job1-Web#1]
## 💡 Issue

네비게이션 바 기능 구현 및 CSS 작업

## 📝  todo
- [ ] todo !
- [x] 로고(새로고침) 및 각 뷰로 이동하는 기능 구현
- [x] 로그인, 마이페이지 이동 기능 구현
- [x] 레이아웃 틀 구성
- [ ] 반응형 디자인
- [x] CSS 
    - [x] 선택시 배경색으로 선택 여부 표시

## 📸 Screenshot

<img width="662" alt="image" src="https://github.com/Hongmoon-gak/Job1-Web/assets/121475533/1d74c0c7-fa21-4455-8fc9-2818f7b5a83d">
