### ISSUE TITLE
[FEAT] 미리보기 뷰 구현

### ISSUE THREAD

**Issue by ju1e3718** [Hongmoon-gak/Job1-Web#14]
## 💡 Issue

검색 결과 나오는 법률, 게시판, 새소식/뉴스 미리보기 뷰 구현 및 CSS 작업

## 📝  todo
- [ ] todo !

- [ ] 게시판 미리보기를 연결하여 미리보기 컴포넌트 구현
- [ ] 검색 시 나오는 창에 법률, 게시판, 새소식/뉴스 순으로 보이도록 구현
- [ ] 게시판 미리보기에서 사용한 CSS 적용

## 📸 Screenshot

<img width="374" alt="스크린샷 2023-07-22 103425" src="https://github.com/Hongmoon-gak/Job1-Web/assets/81310250/90171d8b-61e2-46b6-a724-ea9ee9fa50dc">
