### ISSUE TITLE
[FEAT] 게시판 기능 구현

### ISSUE THREAD

**Issue by jh2ee** [Hongmoon-gak/Job1-Web#24]
## 💡 Issue

게시판 미리보기 기능 구현
게시글 작성 뷰 구현
게시글 작성, 수정, 삭제 기능 구현
게시글 좋아요 기능 구현(인기 게시물 처리 로직 구현)

## 📝  todo
- [ ] todo !
- [ ] 게시판 미리보기 기능 구현
- [ ] 게시글 작성 뷰 구현
    - [ ] 뷰 구현
    - [ ] CSS 
- [ ] 게시글 작성 기능
    - [x] 작성  
    - [ ] 수정
    - [ ] 삭제
    - [ ] 태그 선택
- [ ] 게시물 상세 보기 뷰 구현
    - [ ] 뷰 구현
    - [ ] CSS
    - [ ] 댓글 기능
    - [ ] 댓글 좋아요 기능
    - [ ] 게시글 좋아요 기능 구현(인기 게시물 처리 로직 구현)
    - [ ] 스크랩 기능

## 📸 Screenshot

<img width="351" alt="image" src="https://github.com/Hongmoon-gak/Job1-Web/assets/121475533/0f0ef5af-c006-4c69-900e-7d93ebb8b5c8">
<img width="234" alt="image" src="https://github.com/Hongmoon-gak/Job1-Web/assets/121475533/f4f90eaa-9af2-4b51-b103-6114b07d7ec1">
<img width="418" alt="image" src="https://github.com/Hongmoon-gak/Job1-Web/assets/121475533/9e1e8986-5ddc-4f39-8c68-1e485982cfed">
