### ISSUE TITLE
[FEAT] Main화면 More Info 뷰 구현

### ISSUE THREAD

**Issue by jh2ee** [Hongmoon-gak/Job1-Web#3]
## 💡 Issue

Main 화면에 표시될 More Info 구현
각 상담기관 표시할 컴포넌트 구현

## 📝  todo
- [x] todo !
- [x] 상담기관 정보 담을 카드 구현
- [x] 이미지, 텍스트 클릭 시 상담기관 사이트로 이동
- [x] 연락처 클릭 시 상담기관 전화번호 복사

## 📸 Screenshot

<img width="564" alt="image" src="https://github.com/Hongmoon-gak/Job1-Web/assets/121475533/d73c1591-3aa1-4cc8-97da-a7f46e92bca0">
