### ISSUE TITLE
[FEAT] 마이페이지 구현

### ISSUE THREAD

**Issue by ju1e3718** [Hongmoon-gak/Job1-Web#32]
## 💡 Issue

내가 쓴 글, 댓글 및 스크랩 한 글 볼 수 있는 마이페이지 기능 구현

## 📝  todo
- [ ] todo !

- [ ] 글, 댓글, 스크랩 글 볼 수 있는 뷰 구현
- [ ] 네브바 유저 정보 클릭 시 마이페이지 갈 수 있는 창 구현
- [ ] 로그인 시 네브바에 유저 정보 나오도록 수정
- [ ] 유저 정보에 따른 글 내용 볼 수 있도록 구현

## 📸 Screenshot

<img width="454" alt="스크린샷 2023-08-28 160858" src="https://github.com/Hongmoon-gak/Job1-Web/assets/81310250/441fca22-fe45-4209-bacc-1ca8fde4ff40">
<img width="112" alt="스크린샷 2023-08-28 160906" src="https://github.com/Hongmoon-gak/Job1-Web/assets/81310250/b1cddda8-032f-4078-8916-8cc60e2dc24d">
