### ISSUE TITLE
[FEAT] Main화면 게시판 미리보기 뷰 구현

### ISSUE THREAD

**Issue by ju1e3718** [Hongmoon-gak/Job1-Web#7]
## 💡 Issue

메인화면에 나오는 HOT, NEW 게시판 미리보기 기능 구현 및 CSS 작업

## 📝  todo
- [x] todo !

- [x] 게시판 글 제목, 좋아요, 날짜 나오는 컴포넌트 구현
- [x] 글 제목 클릭 시 해당 게시물로 이동
- [x] HOT, NEW 글자 클릭 시 선택된 게시판 색상 변경 및 하단 글 내용 변경
- [x] css 작업
- [x] 글쓰기 버튼 클릭 시 글쓰기 뷰로 이동

## 📸 Screenshot

<img width="705" alt="스크린샷 2023-07-20 101711" src="https://github.com/Hongmoon-gak/Job1-Web/assets/81310250/f3bd9662-18e1-4965-a21d-2c13f61a7f5e">

**Comment by jh2ee** [comment]
@ju1e3718 반응형도 생각해야 해서 reopen 했습니다
